management:
  security:
    enabled: false
    
server:
  port: 8086
  
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 3
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka
      
logging:
  level:
    com.rueggerllc.provider: debug
  file: C:\logs\Consumer.log