management:
  security:
    enabled: false
    
server:
  port: 8888

  
spring:
  cloud:
    config:
      server:
        git:
          #uri: chris@captain:/home/chris/repos/captain-config.git
          uri: chris@darwin:/home/chris/repos/darwin-config.git
          #uri: git@github.com:rueggerc/config-data.git
      label: master
          
        
logging:
  level:
    com.rueggerllc.book: debug
  file: C:\logs\ConfigServer.log
    